### ISSUE TITLE
Light bug on entities - 1.20.1 Forge - 47.4.47

### ISSUE THREAD

**Issue by Wenzgate** [SrRapero720/WATERFrAMES#21]
Hey, I'm using the mods (waterframe, watermedia and creativeCore) and try few versions of it with none other (without rubidium and oculus too) in 1.20.1

I noticed that the brightness of the waterframe affected the brightness of other entities (chests, beds, dropped items, etc).

If brightness = 1.0, no problem, but once lowered, the problem appears.

I don't know if it's directly linked to the mods, but I can't find any solutions. That's why I wanted to highlight this bug.

thank you

![2023-09-12_18 15 12](https://github.com/SrRapero720/waterframes/assets/95314422/62e60f9e-4d0b-4e67-afc0-40ce66dd9f76)
![2023-09-12_18 15 25](https://github.com/SrRapero720/waterframes/assets/95314422/2246993c-041a-4d2c-9e1a-c385c797a056)
![2023-09-12_18 15 38](https://github.com/SrRapero720/waterframes/assets/95314422/753ac279-4c24-408e-ba83-8e92870bb7a6)

**Comment by SrRapero720** [comment]
i really hope Iris shaders and sodium finally decide to make a official port to NeoForge, i am tired of the shitty asek ports

**Comment by SrRapero720** [comment]
can you test with this version? i cannot reproduce it
https://legacy.curseforge.com/minecraft/mc-mods/waterframes/files/4833018

**Comment by SrRapero720** [comment]
fixed on 2.0.0-beta2.1
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/4860362
https://modrinth.com/mod/waterframes/version/1.20.1-2.0.0-beta2.1

**Comment by BrangGit** [comment]
Hi, the issue still occurs with the 2.0.0-beta5.1 version, with built in shaders. Different Forge version tho.

![2024-03-30_13 43 10](https://github.com/SrRapero720/waterframes/assets/42695438/18c678b2-83b4-45eb-b8e3-e1861579909c)
![2024-03-30_13 43 22](https://github.com/SrRapero720/waterframes/assets/42695438/7d46df93-2b1d-40dc-8295-8059e352fbde)
---
Minecraft 1.20.1
Forge 47.2.19
Modlist : 
- CreativeCore 2.11.25
- WaterFrames 2.0.0-beta5.1
- WaterMedia 2.0.27-beta

I hope this can help, thanks for your work and for this amazing mod ! :)

**Comment by SrRapero720** [comment]
see #32
