### ISSUE TITLE
[2.1.20] Crash clicking on a frame when WaterVision is missing 

### ISSUE THREAD

**Issue by WhiteMemory99** [SrRapero720/WATERFrAMES#222]
I'm unable to open the player GUI after updating to v2.1.20 on fabric 1.21.1.

**Steps to reproduce:**
– Put a frame in your world.
– Right click to open the GUI.
– Experience the crash instead.

**Logs:**
latest.log: https://mclo.gs/fRLbgzf
crash report: https://mclo.gs/kbWujBr

**Comment by SrRapero720** [comment]
I reuploaded the build, should work now

**Comment by WhiteMemory99** [comment]
https://mclo.gs/zkhy45V

Unfortunately, It's still crashing even with the updated jar

> I reuploaded the build, should work now

**Comment by SrRapero720** [comment]
I swear this was not intentional, but please install WaterVision too as a workarround.

**Comment by SrRapero720** [comment]
The 2.1.21 for 1.20.1 got uploaded broken because mixins decide to had a stroke, i need to fix my dev workspace
